#!/usr/bin/env node
/**
 * Build the mobile PWA INTO the Worker so the fixed workers.dev URL is a
 * fully-installable PWA (UI + manifest + icons) — no tunnel needed.
 *
 * Inlines ui/mobile.html/css/js into mobile_embed.js and bundles the manifest
 * + icons (base64) into mobile_assets.js. Run before deploying
 * (cloud/deploy.sh does it automatically), and commit the generated files.
 *
 *   node cloud/build-embed.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ui = join(root, "ui");
const assets = join(root, "cloud", "worker", "assets");
const outHtml = join(root, "cloud", "worker", "src", "mobile_embed.js");
const outAssets = join(root, "cloud", "worker", "src", "mobile_assets.js");

// ---- 1) mobile UI (self-contained) ----
const html = readFileSync(join(ui, "mobile.html"), "utf8");
const css = readFileSync(join(ui, "mobile.css"), "utf8");
const js = readFileSync(join(ui, "mobile.js"), "utf8");
let page = html.replace(
  /<link rel="stylesheet" href="\/mobile\.css">/,
  () => `<style>\n${css}\n</style>`,
).replace(
  /<script src="\/mobile\.js"><\/script>/,
  () => `<script>\n${js}\n</script>`,
);
const bootstrap = `<script>\n(function(){var c=null;try{c=localStorage.getItem("phai.companion.cloud");}catch(e){}if(!c){try{localStorage.setItem("phai.companion.cloud",location.origin);}catch(e){}}})();\n<\/script>`;
page = page.replace("<body", bootstrap + "<body");

writeFileSync(outHtml,
  `/* AUTO-GENERATED by cloud/build-embed.mjs — do not edit by hand. */\nexport const MOBILE_HTML = ${JSON.stringify(page)};\n`);
console.log(`[embed] wrote ${outHtml} (${(page.length / 1024).toFixed(1)} KiB)`);

// ---- 2) manifest + icons (PWA install needs these served same-origin) ----
const manifest = JSON.parse(readFileSync(join(ui, "manifest.webmanifest"), "utf8"));
// point the installed app at the worker root (served by the worker)
manifest.start_url = "/";
const icons = {
  "/icons/icon-192.png": readFileSync(join(assets, "icon-192.png")).toString("base64"),
  "/icons/icon-512.png": readFileSync(join(assets, "icon-512.png")).toString("base64"),
  "/icons/icon-maskable-512.png": readFileSync(join(assets, "icon-maskable-512.png")).toString("base64"),
  "/apple-touch-icon.png": readFileSync(join(assets, "apple-touch-icon.png")).toString("base64"),
};
writeFileSync(outAssets,
  `/* AUTO-GENERATED by cloud/build-embed.mjs — do not edit by hand. */\nexport const MANIFEST = ${JSON.stringify(manifest)};\nexport const ICONS = ${JSON.stringify(icons)};\n`);
console.log(`[embed] wrote ${outAssets} (${Object.values(icons).join("").length / 1024 / 1024 * 1.33 | 0} KiB base64)`);
