#!/usr/bin/env node
/**
 * Build the mobile PWA INTO the Worker so the fixed workers.dev URL opens the
 * companion UI directly (no tunnel needed for cloud mode).
 *
 * Inlines ui/mobile.html + mobile.css + mobile.js into a single self-contained
 * HTML string exported from cloud/worker/src/mobile_embed.js. Run this before
 * deploying (cloud/deploy.sh does it automatically), and commit the generated
 * file so the worker tests keep working.
 *
 *   node cloud/build-embed.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ui = join(root, "ui");
const out = join(root, "cloud", "worker", "src", "mobile_embed.js");

const html = readFileSync(join(ui, "mobile.html"), "utf8");
const css = readFileSync(join(ui, "mobile.css"), "utf8");
const js = readFileSync(join(ui, "mobile.js"), "utf8");

// inline the css + js into the html so it's one self-contained document
let page = html.replace(
  /<link rel="stylesheet" href="\/mobile\.css">/,
  () => `<style>\n${css}\n</style>`,
).replace(
  /<script src="\/mobile\.js"><\/script>/,
  () => `<script>\n${js}\n</script>`,
);

// add a tiny inline bootstrap that defaults the portable base to the page's
// own origin, so opening the workers.dev URL works with zero config
const bootstrap = `<script>\n(function(){try{var s=JSON.parse(localStorage.getItem("phai.companion.state")||"{}")||{};}catch(e){var s={};}if(!s.cloudBase){try{localStorage.setItem("phai.companion.cloud",location.origin);}catch(e){}}})();\n<\/script>`;
page = page.replace("<body", bootstrap + "<body");

// JSON-encode safely
const encoded = JSON.stringify(page);
const banner = `/* AUTO-GENERATED by cloud/build-embed.mjs — do not edit by hand.
   Regenerate after UI changes: node cloud/build-embed.mjs (deploy.sh does it). */
export const MOBILE_HTML = ${encoded};\n`;
writeFileSync(out, banner);
console.log(`[embed] wrote ${out} (${(encoded.length / 1024).toFixed(1)} KiB)`);
